apiVersion: v1
kind: Service
metadata:
  name: progress-watchdog
  labels:
    app.kubernetes.io/name: 'progress-watchdog'
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: 'progress-watchdog'
    app.kubernetes.io/instance: {{ .Release.Name }}